from fastapi import APIRouter
from server.api.v1 import (
    state,
    action,
    settings,
    rio,
    scoreboards,
    game_pool,
    rotation,
    stats,
    layouts,
    branding,
    startgg,
    challonge,
    controller,
    announcements,
    logs,
    assets,
    visualizer,
    participants,
    match,
    matchup,
    schedule,
    commentary,
    playerplates,
    postgame,
    design,
)

router_v1 = APIRouter(
    prefix="/api/v1",
    tags=["api","api_v1"]
)

router_v1.include_router(state.router)
router_v1.include_router(action.router)
router_v1.include_router(settings.router)
router_v1.include_router(rio.router)
router_v1.include_router(scoreboards.router)
router_v1.include_router(game_pool.router)
router_v1.include_router(rotation.router)
router_v1.include_router(stats.router)
router_v1.include_router(layouts.router)
router_v1.include_router(branding.router)
router_v1.include_router(startgg.router)
router_v1.include_router(challonge.router)
router_v1.include_router(controller.router)
router_v1.include_router(announcements.router)
router_v1.include_router(logs.router)
router_v1.include_router(assets.router)
router_v1.include_router(visualizer.router)
router_v1.include_router(participants.router)
router_v1.include_router(match.router)
router_v1.include_router(match.bind_router)
router_v1.include_router(matchup.router)
router_v1.include_router(schedule.router)
router_v1.include_router(commentary.router)
router_v1.include_router(playerplates.router)
router_v1.include_router(postgame.router)
router_v1.include_router(design.router)