#!/usr/bin/env python3
"""Resolve and freeze the application version.

The version is the single source of truth for what users see in the
About panel and on the GitHub Release. Resolution order:

  1. `git describe --tags --always --dirty` — works in any clone with
     git history. On an exact tag (e.g. `v1.1.0`) returns "1.1.0".
     On commits past a tag, returns "1.1.0-3-gabcdef[-dirty]". With
     no tags, returns the short SHA (which the CI guard catches).
  2. Read `server/_version.py` — written by this script during build,
     used by frozen artifacts (PyInstaller bundles, Vite-built dist)
     where `git` is not available at runtime.
  3. Fallback "0.0.0-dev" — running from a tarball with no git and
     no frozen `_version.py`. Visible in the UI as a hint that the
     build is unidentified.

Usage:
  As a library:
      from freeze_version import resolve_version
      print(resolve_version())

  As a CLI (writes `server/_version.py` and prints the version):
      python scripts/freeze-version.py            # writes default path
      python scripts/freeze-version.py --write path/to/_version.py
      python scripts/freeze-version.py --print    # print only, no write
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FROZEN_PATH = REPO_ROOT / "server" / "_version.py"
FALLBACK_VERSION = "0.0.0-dev"


def _git_describe(repo: Path = REPO_ROOT) -> str | None:
    """Run `git describe`. Returns None if git is unavailable or repo has no
    history. Strips the leading "v" so "v1.1.0" -> "1.1.0".
    """
    try:
        out = subprocess.run(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=repo,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if out.returncode != 0:
        return None
    desc = out.stdout.strip()
    if not desc:
        return None
    # Strip a leading "v" only when the tag prefix actually matches a
    # version-looking string ("v1.2.3" or "v1.2.3-…"); leave plain SHAs alone.
    if desc.startswith("v") and len(desc) > 1 and desc[1].isdigit():
        desc = desc[1:]
    return desc


def _read_frozen(path: Path = DEFAULT_FROZEN_PATH) -> str | None:
    """Import-free read of VERSION from a generated _version.py.

    We do a flat parse rather than `import` so this works before the server
    package is set up (e.g. during PyInstaller bootstrap) and so a malformed
    file can't execute arbitrary code.
    """
    if not path.is_file():
        return None
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("VERSION") and "=" in line:
                _, _, rhs = line.partition("=")
                return rhs.strip().strip('"').strip("'") or None
    except OSError:
        return None
    return None


def resolve_version(repo: Path = REPO_ROOT) -> str:
    """Resolve the canonical version string. See module docstring."""
    return (
        _git_describe(repo)
        or _read_frozen(DEFAULT_FROZEN_PATH)
        or FALLBACK_VERSION
    )


def write_frozen(version: str, path: Path = DEFAULT_FROZEN_PATH) -> None:
    """Write VERSION to a Python module so frozen builds can read it.

    Generated; should be gitignored. Idempotent — overwrites on each run.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        '"""Generated by scripts/freeze-version.py — do not edit by hand."""\n'
        f'VERSION = "{version}"\n',
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Resolve and freeze app version.")
    parser.add_argument(
        "--write",
        type=Path,
        default=DEFAULT_FROZEN_PATH,
        help=f"Path to write _version.py (default: {DEFAULT_FROZEN_PATH.relative_to(REPO_ROOT)})",
    )
    parser.add_argument(
        "--print",
        dest="print_only",
        action="store_true",
        help="Print the resolved version and exit without writing.",
    )
    args = parser.parse_args(argv)

    version = resolve_version()
    if not args.print_only:
        write_frozen(version, args.write)
    print(version)
    return 0


if __name__ == "__main__":
    sys.exit(main())
